###############################################################################
#####################################  A12N  ##################################
###############################################################################

.a12n:
  variables:
    SERVICE: a12n
  only:
    changes:
      - heka/a12n/k8s-template.yml

###################################  DEPLOY  ##################################

deploy:a12n:
  needs:
    - deploy:project
  extends:
    - .deploy_only
    - .deploy
    - .a12n
  only:
    variables: ["$_ == null"]

##################################  DESTROY  ##################################

destroy:a12n:
  needs:
    - deploy:a12n
  extends:
    - .deploy_only
    - .destroy
    - .a12n
  only:
    variables: ["$_ == null"]
