###############################################################################
####################################  A12N  ###################################
###############################################################################

.a12n:
  variables:
    SERVICE: a12n
  only:
    changes:
    - heka/a12n/k8s-template.yml

###################################  DEPLOY  ##################################

deploy:a12n:dev:
  needs:
  - deploy:project:dev
  extends:
  - .deploy_only
  - .deploy
  - .dev
  - .a12n
  only:
    variables: ["$_ == null"]  # [GCR:Note] This is our hacky way to say "true"

deploy:a12n:prod:
  needs:
  - deploy:project:prod
  extends:
  - .deploy_only
  - .deploy
  - .prod
  - .a12n
  only:
    variables: ["$_ == null"]  # [GCR:Note] This is our hacky way to say "true"
