###############################################################################
#################################  SCHEDULER  #################################
###############################################################################

.scheduler:
  variables:
    SERVICE: scheduler
  only:
    changes:
    - heka/scheduler/k8s-template.yml

###################################  DEPLOY  ##################################

deploy:scheduler:dev:
  needs:
  - deploy:project:dev
  extends:
  - .deploy_only
  - .deploy
  - .dev
  - .scheduler
  only:
    variables: ["$_ == null"]  # [GCR:Note] This is our hacky way to say "true"

deploy:scheduler:prod:
  needs:
  - deploy:project:prod
  extends:
  - .deploy_only
  - .deploy
  - .prod
  - .scheduler
  only:
    variables: ["$_ == null"]  # [GCR:Note] This is our hacky way to say "true"
