###############################################################################
##################################  SCHEDULER  ################################
###############################################################################

.scheduler:
  variables:
    SERVICE: scheduler
  only:
    changes:
      - heka/scheduler/k8s-template.yml

###################################  DEPLOY  ##################################

deploy:scheduler:
  needs:
    - deploy:project
  extends:
    - .deploy_only
    - .deploy
    - .scheduler
  only:
    variables: ["$_ == null"]

##################################  DESTROY  ##################################

destroy:scheduler:
  needs:
    - deploy:scheduler
  extends:
    - .deploy_only
    - .destroy
    - .scheduler
  only:
    variables: ["$_ == null"]
