###############################################################################
###################################  FRONTEND  ################################
###############################################################################

.frontend:
  variables:
    SERVICE: frontend
  only:
    changes:
      - heka/frontend/**/*

###################################  BUILD  ###################################

build:frontend:
  extends:
    - .all_stages
    - .build
    - .frontend

####################################  TEST  ###################################

test:frontend:
  needs:
    - build:frontend
  extends:
    - .all_stages
    - .test
    - .frontend
  script:
    # Tests go here
    - exit 0

####################################  PUSH  ###################################

push:frontend:
  needs:
    - test:frontend
  extends:
    - .all_stages
    - .push
    - .frontend

###################################  DEPLOY  ##################################

deploy:frontend:
  needs:
    - push:frontend
    - deploy:project
  extends:
    - .all_stages
    - .deploy
    - .frontend

deploy_only:frontend:
  needs:
    - deploy:project
  extends:
    - .deploy_only
    - .deploy
    - .frontend

##################################  DESTROY  ##################################

destroy:frontend:
  needs:
    - deploy:frontend
  extends:
    - .all_stages
    - .destroy
    - .frontend

destroy_only:frontend:
  needs:
    - deploy_only:frontend
  extends:
    - .deploy_only
    - .destroy
    - .frontend
