###############################################################################
###################################  LAUNCHER  ################################
###############################################################################

.launcher:
  variables:
    SERVICE: launcher
  only:
    changes:
      - heka/launcher/k8s-template.yml

###################################  DEPLOY  ##################################

deploy:launcher:
  needs:
    - deploy:project
  extends:
    - .deploy_only
    - .deploy
    - .launcher
  only:
    variables: ["$_ == null"]

##################################  DESTROY  ##################################

destroy:launcher:
  needs:
    - deploy:launcher
  extends:
    - .deploy_only
    - .destroy
    - .launcher
  only:
    variables: ["$_ == null"]
