###############################################################################
###################################  PROJECT  #################################
###############################################################################

###################################  DEPLOY  ##################################

deploy:project:
  stage: 🚢 Deploy Common
  environment:
    name: ${CI_COMMIT_BRANCH}
  needs: []
  extends:
  - .deploy
  only:
    variables: ["$_ == null"]

##################################  DESTROY  ##################################

destroy:project:
  environment:
    name: ${CI_COMMIT_BRANCH}
  extends:
  - .destroy

##################################  INCLUDES  #################################

include:
- local: /heka/a12n/.gitlab-ci.yml
- local: /heka/c13s/.gitlab-ci.yml
- local: /heka/launcher/.gitlab-ci.yml
- local: /heka/frontend/.gitlab-ci.yml
- local: /heka/admin/.gitlab-ci.yml
- local: /heka/scheduler/.gitlab-ci.yml
- local: /heka/tasks/.gitlab-ci.yml
