###############################################################################
#####################################  C13S  ##################################
###############################################################################

.c13s:
  variables:
    SERVICE: c13s
  only:
    changes:
      - heka/c13s/**/*

###################################  BUILD  ###################################

build:c13s:
  extends:
    - .all_stages
    - .build
    - .c13s

####################################  TEST  ###################################

test:c13s:
  needs:
    - build:c13s
  extends:
    - .all_stages
    - .test
    - .c13s
  script:
    # Tests go here
    - exit 0

####################################  PUSH  ###################################

push:c13s:
  needs:
    - test:c13s
  extends:
    - .all_stages
    - .push
    - .c13s

###################################  DEPLOY  ##################################

deploy:c13s:
  needs:
    - push:c13s
    - deploy:project
  extends:
    - .all_stages
    - .deploy
    - .c13s

deploy_only:c13s:
  needs:
    - deploy:project
  extends:
    - .deploy_only
    - .deploy
    - .c13s

##################################  DESTROY  ##################################

destroy:c13s:
  needs:
    - deploy:c13s
  extends:
    - .all_stages
    - .destroy
    - .c13s

destroy_only:c13s:
  needs:
    - deploy_only:c13s
  extends:
    - .deploy_only
    - .destroy
    - .c13s
