###############################################################################
####################################  ADMIN  ##################################
###############################################################################

.admin:
  variables:
    SERVICE: admin
  only:
    changes:
      - heka/admin/k8s-template.yml

###################################  DEPLOY  ##################################

deploy:admin:
  needs:
    - deploy:project
  extends:
    - .deploy_only
    - .deploy
    - .admin
  only:
    variables: ["$_ == null"]

##################################  DESTROY  ##################################

destroy:admin:
  needs:
    - deploy:admin
  extends:
    - .deploy_only
    - .destroy
    - .admin
  only:
    variables: ["$_ == null"]
